### ISSUE TITLE
Infinite Recursion possible in 2.4

### ISSUE THREAD

**Issue by dave-v** [jazzband/django-formtools#220]
We have a `condition_dict` containing the following function:
```py
def need_further_steps(wizard):
    data = wizard.get_cleaned_data_for_step("0") or {}
    if data.get("no_invoices_needed", False):
        return False
    return True
```
The call to `WizardView.get_cleaned_data_for_step` then calls `WizardView.get_form`, which used to reference `self.form_list`, but the following commit changes this to `self.get_form_list()`, which then calls the user-supplied `condition_dict` functions, which then calls our `need_further_steps` function above, which calls `WizardView.get_cleaned_data_for_step`, and so on ad infinitum.
https://github.com/jazzband/django-formtools/commit/533a83053deab2adeb72de079e813aae78b03c1a

Perhaps our custom condition function is bad, but it doesn't seem too unreasonable?

**Comment by claudep** [comment]
@stuaxo, @schinckel, any idea about how to avoid that regression?

**Comment by schinckel** [comment]
I think I’ve had similar issues. I’ll try to have a look later tonight to see how I got around it.

**Comment by schinckel** [comment]
Okay, I've found the similar problem I came across. I think it's the "same" problem, just a different approach.

I had code in `get_form_list` that needed to see cleaned data from other steps, which triggers the infinite co-recursion.

My workaround was to get the raw data instead, and build up that form and get the cleaned data that way.

We should think about either/both a way to handle this (getting cleaned data from other steps in condition_dict callable), and/or documenting the problem.

**Comment by schinckel** [comment]
Ah, looking at the code, it seems that whilst `get_cleaned_data_for_step(step)` doesn't use `get_form_list()`, it uses `get_form`, which does.

**Comment by schinckel** [comment]
I wonder if it's possible to use a generator that retains knowledge of previous steps: it should be possible for condition_dict to refer to previous steps, but not subsequent steps.

Let me see what I can get to work.

**Comment by stuaxo** [comment]
Maybe get_cleaned_data_step could be behind lru_cache with maxsize None.

**Comment by violuke** [comment]
We're also having the same issue

**Comment by DJJacobs** [comment]
Experiencing the same issue upon update from 2.3 > 2.4. Reverting back to 2.3 for now. Following for updates...

**Comment by violuke** [comment]
The fix of #168 has caused this problem. My understanding is that you should be using the `conditiion_dict` to vary which steps are in the wizard and which are not. I can see why overriding `get_form_list()` would seem like a nice alternative (and maybe simpler to use), but by changing `get_form()` to use `get_form_list()` and solve the request of #168, this makes it impossible to have conditions which look at prior form steps as part of their conditions and therefore **breaks what is probably one of the most common use-cases of this package**.

My opinion is that 533a83053deab2adeb72de079e813aae78b03c1a should be reverted as it tries to allow the same problem to be solved in a new, previously-not-possible, way and breaks the original way of solving the same problem that's been part of this great package for years.

Thanks for your help, we've also had to pin 2.3 due to this being a breaking change for our use of the package.

**Comment by spapas** [comment]
I have a different opinion on this. By being able to override the get_form_list you have complete freedom on the list of forms you're going to display in your wizard. See here some example code from a project where a wizard is created dynamically based on some configuration (taken from the PR_ACTION list of dics):

```
class PilotRequestActionView(..., SessionWizardView):
    ...

    def get_form_list(self):
        form_list = OrderedDict()
        action = self.kwargs["action"]
        has_form = [x for x in PR_ACTIONS if x["code"] == action][0]["has_form"]
        if has_form:
            form_class_str = (
                "PilotRequest"
                + "".join(x.capitalize() for x in action.split("_"))
                + "Form"
            )
            form_class = getattr(forms, form_class_str)
            form_list[action] = form_class
        form_list["submit_req"] = forms.PilotRequestSubmitForm
        return form_list
```

So I can do something like 

```
path(
        "act/<str:action>/<int:pk>/",
        views.ActionView.as_view(),
        name="req-action",
    ),
```

in my urls and create different wizards.

I really don't think that something like that would possible using the condition_dict.

**Comment by schinckel** [comment]
Yeah, the original use case for my patch (and what I've been using as a subclass for many years) was where I needed to _add_ steps dynamically, based upon the submitted data from an earlier step. Specifically, there was a form that needed to be re-used N times, with different initial data.

**Comment by schinckel** [comment]
So the fix I have (linked in this thread), it "works", but there's not a real way to detect that we have attempted to reference data from a subsequent step (and are inside an infinite recursion), until the Python infinite recursion protection kicks in by running out of stack: at that point we can't recover because, well, we are out of stack.

If there was a neat way of detecting we are in a recursive call, then we could try that - but without sniffing the stack, I wasn't able to detect that.

**Comment by stuaxo** [comment]
It probably makes sense to step back and list the places ways the data is referenced at different steps.

**Comment by tilsche** [comment]
We also have this issue that blocks us from upgrading.

**Comment by jsma** [comment]
Please revert 533a83053, which introduced a major bug and was not a proper solution for the new feature request (to dynamically add forms that aren't in the initial `form_list`). For those that require this new feature, please provide a working example of your use cases and how you were doing this prior to 2.4. A proper API needs to be created _and tested_ for this new feature request, without breaking existing documented functionality. That has not been done yet. A proper API shouldn't require any hacks around infinite recursion errors, it should be designed so these errors are impossible.

**Comment by violuke** [comment]
@claudep, @felixxm and @hramezani ([I believe you're the Jazzband leads on this project](https://jazzband.co/projects/django-formtools)) would it be possible for someone to review this thread? There was a major breaking change in 2.4 and a solution needs to be found if possible ASAP. Thank you.

**Comment by schinckel** [comment]
Maybe we should revert the change, and work to find a solution that works later. I just don’t have the time to spend on it now.

**Comment by martey** [comment]
I'm confused about why people are advocating for this change to be reverted "ASAP". Is there a reason why affected people can't stick with 2.3 until a comprehensive solution for this issue is found?

**Comment by jsma** [comment]
@martey, it should be reverted because 2.4 is a broken release that breaks real projects and costs people valuable time and money. It's not very reasonable to expect everyone to find out the hard way that 2.4 is broken, find this issue, and then downgrade to 2.3, when reverting could avoid all of that. To be clear, we don't need to come up with a comprehensive solution for the infinite recursion bug. The changeset that introduced the bug simply needs to be reverted. Once that is done, a comprehensive solution to the _feature request_ (to be able to dynamically _add_ forms that are not present in `form_list`) would need to be developed, documented, and tested before being included in a future release.

@schinckel, are you saying you don't have time for reverting the commit or just that you do not have time to work on a proper solution for the feature request? There is already #222 for reverting the change. In my opinion, 2.4 should be yanked from PyPI in favor of the next release. I could submit a PR to update the changelog. Let us know how we can help. Thanks!

**Comment by schinckel** [comment]
The latter - to come up with a proper solution.

**Comment by martey** [comment]
@jsma I don't think it's fair to assume that everyone uses django-formtools in the same way, or that everyone is affected by this regression. I think people using `condition_dict` callables that call `get_cleaned_data_for_step` (who are affected by this bug) and people using dynamic forms with `get_form_list` *both* have valid use cases.

> Once that is done, a comprehensive solution to the feature request (to be able to dynamically add forms that are not present in form_list) would need to be developed, documented, and tested before being included in a future release.

This already happened (see #62, #168, #209). The "future release" was 2.4.

Calling this a "new feature" or "feature request" is inaccurate, especially since people have been confused by the fact that `form_list` is not generated from `get_form_list` for at least a decade (e.g. [this Stack Overflow question from 2012](https://stackoverflow.com/q/13052224/113527)), probably because the method's docstring has always suggested that this is the case.

> In my opinion, 2.4 should be yanked from PyPI in favor of the next release.

*Removing* 2.4 from PyPI and releasing a new version would prevent people using dynamic forms with `get_form_list` from pinning 2.4. I think this would make things worse, not better.

**Comment by spapas** [comment]
Hey friends! I'd like to propose a solution to this if I may:

For starters, let's agree that we can't use  `get_form_list` if we also use `get_cleaned_data_for_step` somewhere. I think that makes sense, if we use a dynamic form we may add the *same* step over and over so get_cleaned_data_for_step wouldn't even know what to return!

Now, we'll add a 
`FORM_WIZARD_DYNAMIC_FORM_LIST` django setting (we can either set it to True or False by default depending on which behavior we want to keep). Then we'll change `get_form` line that returns the form (here https://github.com/jazzband/django-formtools/blob/master/formtools/wizard/views.py#LL409C9-L409C48) to something like:

```
if settings.FORM_WIZARD_DYNAMIC_FORM_LIST:
  form_class = self.get_form_list()[step]
else:
  form_class = self.form_list[step]
```

Finally, we'll add the following snippet to the start of `get_cleaned_data_for_step`:

```
if settings.FORM_WIZARD_DYNAMIC_FORM_LIST:
  raise Exception("You can't use get_cleaned_data_for_step  when you use a dynamic form list")
```

I think the above should resolve the problem and be a good solution for both people that need to use a dynamic form list and for those that need to retrieve previous steps data.

**Comment by schinckel** [comment]
That's fine, but what if you have a reusable app that does/doesn't, and you use that in your project that has the other setting?

**Comment by martey** [comment]
I agree that a project-wide Django setting is too broad, but this could be fixed by adding a `dynamic_form_list` variable to `WizardView` that defaults to `False`.

**Comment by stuaxo** [comment]
This might be an OK compromise - it's hacky, but may be the only sensible way round this.

Is it possible for someone to post the smallest conditional form wizard here, so we can try out solutions ?

**Comment by fdemmer** [comment]
I propose to not use example projects or code snippets, but actual test code going forward.

To help with that I just opened https://github.com/jazzband/django-formtools/pull/230 which includes a test for using `get_cleaned_data_for_step` in a `condition_dict` callback.

**Comment by fdemmer** [comment]
I think test improvements are dearly needed in this project; my PR is meant as a general improvement of things not just this issue.

Anyway, for the issue at hand you could pull just this commit: https://github.com/jazzband/django-formtools/pull/230/commits/c6d9eda3c1134c2001cac62472826967858b06c7 ... remove the `skip()` and implement "dynamic_form_list" in a way, that does not break it.

**Comment by JanMalte** [comment]
> I'm confused about why people are advocating for this change to be reverted "ASAP". Is there a reason why affected people can't stick with 2.3 until a comprehensive solution for this issue is found?

A reason could be that version 2.4.0 added official support for django v4

Maybe a version 2.3.1 could be released with the old behaviour and official django v4 support?
So we can pin to `<2.4` until the issue is somehow resolved and upgrade/use django v4.

**Comment by violuke** [comment]
And in an ideal world, [SemVer](https://semver.org/) would be used so people could understand version numbers and use modern package managers like [Poetry](https://python-poetry.org/) properly. This being a breaking change could then be safely introduced using version 3.0.0 instead of 2.4.0, if it was wanted (not that I'm sure it should be tbh). Having come from other languages to Python in the last few years, the Python community seems quite out of sync with the rest on the SemVer front and SemVer is really damn handy when managing dependencies.

**Comment by stuaxo** [comment]
OK, so I had a look back at the original PR and a bit of a think -

There are two use cases, one is an API for callers outside the wizard to get a list of forms, and the case where inside get_form we need a list.

If these have separate names we can avoid the issue.

**Comment by schinckel** [comment]
The original use case was to dynamically inject forms: specifically given the input from step A, run n instances of step B with different data, as “sub-steps”.

**Comment by stuaxo** [comment]
In that case is it enough to keep it and people use the solution @spapas proposes if people want to overide get_form ?

**Comment by sagesharp** [comment]
Hi folks! We are also being bitten by this infinite recursion bug. There was an ask for examples of forms with this issue. I don't have the simplest example (as was the ask), but you can take a look at our usage case in the [Outreachy website repository](https://github.com/outreachy/website/blob/master/home/views.py#L432). I've documented steps to reproduce the issue in the [Outreachy website issue tracker](https://github.com/outreachy/website/issues/537)

[Outreachy](https://www.outreachy.org) is an internship program that supports diversity in open source. Outreachy uses django-formtools to have potential interns fill out an application. We receive over 3,000 applications per internship cohort, so we really appreciate this Django package! :heart:

We'll pin our django-formtools version to 2.3 until this issue can be fixed. I'll also take a look at the other solutions posted here. I don't know if I'll have time to make them work before our applications open on January 16, 2023, but I'll try. :sweat_smile:

**Comment by claudep** [comment]
@schinckel, any opinion about the possible fix in #239 ?

**Comment by schinckel** [comment]
Yeah, that looks okay to me.

**Comment by MrkGrgsn** [comment]
I've just submitted a PR that attempts a more complete fix for this problem. Please have a look and give it a test if you've got time.
